version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: DockerFile
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    environment:
      - HTTPS:true

  db:
    container_name: mysql
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jerome_aws_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 6033:3306

  nginx:
    image: nginx:1.23.4
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web

      