version: '3.3'
services:
  web: 
    build:
      context: ./
      dockerfile: DockerFile
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
      - ./certs:/certs
    environment:
      - HTTPS:true
      - SSL_CERT_FILE:/certs/cert.pem
      - SSL_KEY_FILE:/certs/cert-key.pem

  db:
    container_name: mysql
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jerome_aws_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 6033:3306

  nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - 8080:80
    - 8443:443
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  depends_on:
    - web      