version: '3.3'
services:
  web: 
    build:
      dockerfile: DockerFile
    container_name: php-apache
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80
      - 8443:443

  db:
    container_name: mysql
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jerome_aws_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 6033:3306